export const browserCoreExamples = [
  "reecenbot browser status",
  "reecenbot browser start",
  "reecenbot browser stop",
  "reecenbot browser tabs",
  "reecenbot browser open https://example.com",
  "reecenbot browser focus abcd1234",
  "reecenbot browser close abcd1234",
  "reecenbot browser screenshot",
  "reecenbot browser screenshot --full-page",
  "reecenbot browser screenshot --ref 12",
  "reecenbot browser snapshot",
  "reecenbot browser snapshot --format aria --limit 200",
  "reecenbot browser snapshot --efficient",
  "reecenbot browser snapshot --labels",
];

export const browserActionExamples = [
  "reecenbot browser navigate https://example.com",
  "reecenbot browser resize 1280 720",
  "reecenbot browser click 12 --double",
  'reecenbot browser type 23 "hello" --submit',
  "reecenbot browser press Enter",
  "reecenbot browser hover 44",
  "reecenbot browser drag 10 11",
  "reecenbot browser select 9 OptionA OptionB",
  "reecenbot browser upload /tmp/file.pdf",
  'reecenbot browser fill --fields \'[{"ref":"1","value":"Ada"}]\'',
  "reecenbot browser dialog --accept",
  'reecenbot browser wait --text "Done"',
  "reecenbot browser evaluate --fn '(el) => el.textContent' --ref 7",
  "reecenbot browser console --level error",
  "reecenbot browser pdf",
];
